# Generated by Django 5.0.6 on 2024-05-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Physio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
