# Generated by Django 5.0.6 on 2024-05-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physio', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_images',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='Physio.event')),
            ],
        ),
    ]
