# Generated by Django 5.0.6 on 2024-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physio', '0003_remove_event_event_images_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('consultation', 'consultation'), ('physio_therapy', 'physio_therapy'), ('MEDECINE GENERALE', 'MEDECINE GENERALE'), ('IMAGERIE MEDICALE', 'IMAGERIE MEDICALE'), ('REHABILITATION FONCTIONNELLE', 'REHABILITATION FONCTIONNELLE')], max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
    ]
