# Generated by Django 5.0.6 on 2024-05-19 11:15

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physio', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('consultation', 'consultation'), ('physio_therapy', 'physio_therapy'), ('MEDECINE GENERALE', 'MEDECINE GENERALE'), ('IMAGERIE MEDICALE', 'IMAGERIE MEDICALE'), ('REHABILITATION FONCTIONNELLE', 'REHABILITATION FONCTIONNELLE')], max_length=100, unique=True),
        ),
    ]
