# Generated by Django 5.0.6 on 2024-05-23 06:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physio', '0007_alter_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_en',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('consultation', 'consultation'), ('physio_therapy', 'physio_therapy'), ('MEDEINE GENERALCE', 'MEDECINE GENERALE'), ('IMAGERIE MEDICALE', 'IMAGERIE MEDICALE'), ('REHABILITATION FONCTIONNELLE', 'REHABILITATION FONCTIONNELLE')], max_length=100, unique=True),
        ),
    ]
